### ISSUE TITLE
support for nvidia-docker GPUs?

### ISSUE THREAD

**Issue by dlbears** [SAP/machine-learning-lab#10]
I dont see any documentation about attaching GPUs, is this a supported feature?

**Comment by raethlein** [comment]
Hey @dlbears, thanks for your interest and the question! Currently, attaching GPUs in ml-lab is not possible but it's on the roadmap. Though, I can highly recommend those components: [ml-workspace](https://github.com/ml-tooling/ml-workspace) and [ml-hub](https://github.com/ml-tooling/ml-hub). With them, you can easily launch a single workspace or administer multiple ones (ml-hub) that leverage underlying GPUs.
