### ISSUE TITLE
Docker base image not reachable

### ISSUE THREAD

**Issue by ericksantillanp** [SAP/machine-learning-lab#5]
**Describe your request:**

The base image used for the cleaning job uses a base image that it's not reachable. The image could be hosted on docker-hub or here on github, however it should be moved so that the image can be pulled.

**Which page or section is this issue related to?**

https://github.com/SAP/machine-learning-lab/blob/2d7a9ecae3780a5ecfe323e55b5d555ac41ce261/services/cleaning-job/Dockerfile#L1

**Comment by raethlein** [comment]
Hey @ericksantillanp, thanks for opening the issue. I removed the legacy service in commit d07bf3a
